### ISSUE TITLE
Python

### ISSUE THREAD

**Issue by ayhama16** [pdf-raku/PDF-Tags-Reader-raku#1]
Great script, thank you so much!

**Comment by ayhama16** [comment]
aum@aum-2 bin % ./pdf-tag-dump.pl 48027.pdf                
===SORRY!=== Error while compiling /Users/aum/Downloads/PDF-Tags-Reader-raku-main/bin/./pdf-tag-dump.pl
Could not find PDF::Class in:
    inst#/Users/aum/.raku
    inst#/usr/local/Cellar/rakudo-star/2022.02/share/perl6/site
    inst#/usr/local/Cellar/rakudo-star/2022.02/share/perl6/vendor
    inst#/usr/local/Cellar/rakudo-star/2022.02/share/perl6/core
    ap#
    nqp#
    perl5#

I have this error, can you help me to run the script?
Thank you so much!

**Comment by ayhama16** [comment]
Maybe I need to instlal some modules?

**Comment by dwarring** [comment]
Thanks, glad you got it to work.
